import cv2 as cv

#UAS4STEM constants
TARGET_NUM = 12
TARGETS = ("TOWER", "TREE", "RUBBLE", "LUMBER", "PIPES", "POWER_LINES", "INTERSECTION", "TRASH", "PERSONNEL", "BRIDGE", "HARDWARE", "EQUIPMENT")
TARGET_SIDE_LENGTH = 4

#Global constants
EARTH_RADIUS = 6378137.0
FEET_TO_METERS = 0.3048

#Camera constants
WIDTH, HEIGHT = 1280, 720
CAMERA_FPS = 20
RECORDING_FPS = 20
EXPOSURE = 2000
GAIN = 1.1
SATURATION = 0
CONTRAST = 1.1
CENTER_THRESHOLD = 100
FONT = cv.FONT_HERSHEY_SIMPLEX
CAMERA_FORMAT = "BGR888"
RECORDING_FOURCC = cv.VideoWriter_fourcc(*'MJPG')

#Mission constants
MOVE_TIME = 2
TARGET_COOLDOWN = 5
CENTERING_TIMEOUT = 30
ALREADY_FOUND_MAX_THRESHOLD = 2
FOUND_MIN_THRESHOLD = 3

#Drone constants
BAUD = 115200
TAKEOFF_ALTITUDE = 30
ALTITUDE_THRESHOLD = 0.95
STEP_LENGTH = 2
STEP_SPEED = 1.5

#Opencv constants
RATIO_TEST_VALUES = (0.5, 0.5, 0.5, 0.5, 0.5, 0.5, 0.6, 0.5, 0.5, 0.5, 0.5, 0.5)
CONTOUR_VALUE_THRESHOLD = 150
CONTOUR_AREA_MIN_THRESHOLD = 150
SOLIDITY_MAX_THRESHOLD = 0.1
CONTOUR_POLYDP_EPSILON = 0.02
SIDE_NUM_THRESHOLD = 0
CONTOUR_OUTLINE_COLOR = (0, 255, 0)
CONTOUR_OUTLINE_THICKNESS = 2
